/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pathfinding_visualizer;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void fillerTest() {
        App app = new App();
        assertNotNull(app);
    }
}
